/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The main energy source for cooking
 * @export
 */
export const CooktopEnum = {
    Gas: 'GAS',
    Lpg: 'LPG',
    ElectricResistance: 'ELECTRIC_RESISTANCE',
    ElectricInduction: 'ELECTRIC_INDUCTION'
} as const;
export type CooktopEnum = typeof CooktopEnum[keyof typeof CooktopEnum];


export function instanceOfCooktopEnum(value: any): boolean {
    for (const key in CooktopEnum) {
        if (Object.prototype.hasOwnProperty.call(CooktopEnum, key)) {
            if (CooktopEnum[key as keyof typeof CooktopEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CooktopEnumFromJSON(json: any): CooktopEnum {
    return CooktopEnumFromJSONTyped(json, false);
}

export function CooktopEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CooktopEnum {
    return json as CooktopEnum;
}

export function CooktopEnumToJSON(value?: CooktopEnum | null): any {
    return value as any;
}

export function CooktopEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CooktopEnum {
    return value as CooktopEnum;
}

