/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Where the household is located
 * @export
 */
export const LocationEnum = {
    OtherTerritories: 'OTHER_TERRITORIES',
    Victoria: 'VICTORIA',
    NewSouthWales: 'NEW_SOUTH_WALES',
    NorthernTerritory: 'NORTHERN_TERRITORY',
    AustralianCapitalTerritory: 'AUSTRALIAN_CAPITAL_TERRITORY',
    Tasmania: 'TASMANIA',
    WesternAustralia: 'WESTERN_AUSTRALIA',
    SouthAustralia: 'SOUTH_AUSTRALIA',
    Queensland: 'QUEENSLAND',
    Overseas: 'OVERSEAS'
} as const;
export type LocationEnum = typeof LocationEnum[keyof typeof LocationEnum];


export function instanceOfLocationEnum(value: any): boolean {
    for (const key in LocationEnum) {
        if (Object.prototype.hasOwnProperty.call(LocationEnum, key)) {
            if (LocationEnum[key as keyof typeof LocationEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LocationEnumFromJSON(json: any): LocationEnum {
    return LocationEnumFromJSONTyped(json, false);
}

export function LocationEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationEnum {
    return json as LocationEnum;
}

export function LocationEnumToJSON(value?: LocationEnum | null): any {
    return value as any;
}

export function LocationEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LocationEnum {
    return value as LocationEnum;
}

