/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpexWeeklyOtherEnergyCostsByFuelType
 */
export interface OpexWeeklyOtherEnergyCostsByFuelType {
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyOtherEnergyCostsByFuelType
     */
    gas?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyOtherEnergyCostsByFuelType
     */
    lpg?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyOtherEnergyCostsByFuelType
     */
    wood?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyOtherEnergyCostsByFuelType
     */
    petrol?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyOtherEnergyCostsByFuelType
     */
    diesel?: number;
}

/**
 * Check if a given object implements the OpexWeeklyOtherEnergyCostsByFuelType interface.
 */
export function instanceOfOpexWeeklyOtherEnergyCostsByFuelType(value: object): value is OpexWeeklyOtherEnergyCostsByFuelType {
    return true;
}

export function OpexWeeklyOtherEnergyCostsByFuelTypeFromJSON(json: any): OpexWeeklyOtherEnergyCostsByFuelType {
    return OpexWeeklyOtherEnergyCostsByFuelTypeFromJSONTyped(json, false);
}

export function OpexWeeklyOtherEnergyCostsByFuelTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpexWeeklyOtherEnergyCostsByFuelType {
    if (json == null) {
        return json;
    }
    return {
        
        'gas': json['gas'] == null ? undefined : json['gas'],
        'lpg': json['lpg'] == null ? undefined : json['lpg'],
        'wood': json['wood'] == null ? undefined : json['wood'],
        'petrol': json['petrol'] == null ? undefined : json['petrol'],
        'diesel': json['diesel'] == null ? undefined : json['diesel'],
    };
}

export function OpexWeeklyOtherEnergyCostsByFuelTypeToJSON(json: any): OpexWeeklyOtherEnergyCostsByFuelType {
    return OpexWeeklyOtherEnergyCostsByFuelTypeToJSONTyped(json, false);
}

export function OpexWeeklyOtherEnergyCostsByFuelTypeToJSONTyped(value?: OpexWeeklyOtherEnergyCostsByFuelType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gas': value['gas'],
        'lpg': value['lpg'],
        'wood': value['wood'],
        'petrol': value['petrol'],
        'diesel': value['diesel'],
    };
}

