/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpexWeeklyFixedCostsByFuelType
 */
export interface OpexWeeklyFixedCostsByFuelType {
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyFixedCostsByFuelType
     */
    gas?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyFixedCostsByFuelType
     */
    lpg?: number;
    /**
     * 
     * @type {number}
     * @memberof OpexWeeklyFixedCostsByFuelType
     */
    electricity?: number;
}

/**
 * Check if a given object implements the OpexWeeklyFixedCostsByFuelType interface.
 */
export function instanceOfOpexWeeklyFixedCostsByFuelType(value: object): value is OpexWeeklyFixedCostsByFuelType {
    return true;
}

export function OpexWeeklyFixedCostsByFuelTypeFromJSON(json: any): OpexWeeklyFixedCostsByFuelType {
    return OpexWeeklyFixedCostsByFuelTypeFromJSONTyped(json, false);
}

export function OpexWeeklyFixedCostsByFuelTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpexWeeklyFixedCostsByFuelType {
    if (json == null) {
        return json;
    }
    return {
        
        'gas': json['gas'] == null ? undefined : json['gas'],
        'lpg': json['lpg'] == null ? undefined : json['lpg'],
        'electricity': json['electricity'] == null ? undefined : json['electricity'],
    };
}

export function OpexWeeklyFixedCostsByFuelTypeToJSON(json: any): OpexWeeklyFixedCostsByFuelType {
    return OpexWeeklyFixedCostsByFuelTypeToJSONTyped(json, false);
}

export function OpexWeeklyFixedCostsByFuelTypeToJSONTyped(value?: OpexWeeklyFixedCostsByFuelType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gas': value['gas'],
        'lpg': value['lpg'],
        'electricity': value['electricity'],
    };
}

