/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendationActionEnum } from './RecommendationActionEnum';
import {
    RecommendationActionEnumFromJSON,
    RecommendationActionEnumFromJSONTyped,
    RecommendationActionEnumToJSON,
    RecommendationActionEnumToJSONTyped,
} from './RecommendationActionEnum';

/**
 * 
 * @export
 * @interface Recommendation
 */
export interface Recommendation {
    /**
     * 
     * @type {RecommendationActionEnum}
     * @memberof Recommendation
     */
    action: RecommendationActionEnum;
    /**
     * A URL to a resource to give more information about this recommended action.
     * @type {string}
     * @memberof Recommendation
     */
    url?: string;
}



/**
 * Check if a given object implements the Recommendation interface.
 */
export function instanceOfRecommendation(value: object): value is Recommendation {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function RecommendationFromJSON(json: any): Recommendation {
    return RecommendationFromJSONTyped(json, false);
}

export function RecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'action': RecommendationActionEnumFromJSON(json['action']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function RecommendationToJSON(json: any): Recommendation {
    return RecommendationToJSONTyped(json, false);
}

export function RecommendationToJSONTyped(value?: Recommendation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': RecommendationActionEnumToJSON(value['action']),
        'url': value['url'],
    };
}

