/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The main method of space heating
 * @export
 */
export const SpaceHeatingEnum = {
    Wood: 'WOOD',
    Gas: 'GAS',
    Lpg: 'LPG',
    Diesel: 'DIESEL',
    ElectricResistance: 'ELECTRIC_RESISTANCE',
    ElectricHeatPump: 'ELECTRIC_HEAT_PUMP',
    None: 'NONE'
} as const;
export type SpaceHeatingEnum = typeof SpaceHeatingEnum[keyof typeof SpaceHeatingEnum];


export function instanceOfSpaceHeatingEnum(value: any): boolean {
    for (const key in SpaceHeatingEnum) {
        if (Object.prototype.hasOwnProperty.call(SpaceHeatingEnum, key)) {
            if (SpaceHeatingEnum[key as keyof typeof SpaceHeatingEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SpaceHeatingEnumFromJSON(json: any): SpaceHeatingEnum {
    return SpaceHeatingEnumFromJSONTyped(json, false);
}

export function SpaceHeatingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceHeatingEnum {
    return json as SpaceHeatingEnum;
}

export function SpaceHeatingEnumToJSON(value?: SpaceHeatingEnum | null): any {
    return value as any;
}

export function SpaceHeatingEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SpaceHeatingEnum {
    return value as SpaceHeatingEnum;
}

