/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleFuelTypeEnum } from './VehicleFuelTypeEnum';
import {
    VehicleFuelTypeEnumFromJSON,
    VehicleFuelTypeEnumFromJSONTyped,
    VehicleFuelTypeEnumToJSON,
    VehicleFuelTypeEnumToJSONTyped,
} from './VehicleFuelTypeEnum';

/**
 * 
 * @export
 * @interface Vehicle
 */
export interface Vehicle {
    /**
     * 
     * @type {VehicleFuelTypeEnum}
     * @memberof Vehicle
     */
    fuelType: VehicleFuelTypeEnum;
    /**
     * Typical kilometres driven per week by this vehicle
     * @type {number}
     * @memberof Vehicle
     */
    kmsPerWeek?: number;
    /**
     * Whether the household wants to switch to EV
     * @type {boolean}
     * @memberof Vehicle
     */
    switchToEV?: boolean;
}



/**
 * Check if a given object implements the Vehicle interface.
 */
export function instanceOfVehicle(value: object): value is Vehicle {
    if (!('fuelType' in value) || value['fuelType'] === undefined) return false;
    return true;
}

export function VehicleFromJSON(json: any): Vehicle {
    return VehicleFromJSONTyped(json, false);
}

export function VehicleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vehicle {
    if (json == null) {
        return json;
    }
    return {
        
        'fuelType': VehicleFuelTypeEnumFromJSON(json['fuelType']),
        'kmsPerWeek': json['kmsPerWeek'] == null ? undefined : json['kmsPerWeek'],
        'switchToEV': json['switchToEV'] == null ? undefined : json['switchToEV'],
    };
}

export function VehicleToJSON(json: any): Vehicle {
    return VehicleToJSONTyped(json, false);
}

export function VehicleToJSONTyped(value?: Vehicle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fuelType': VehicleFuelTypeEnumToJSON(value['fuelType']),
        'kmsPerWeek': value['kmsPerWeek'],
        'switchToEV': value['switchToEV'],
    };
}

