/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VehicleFuelTypeEnum = {
    Electric: 'ELECTRIC',
    PlugInHybrid: 'PLUG_IN_HYBRID',
    Hybrid: 'HYBRID',
    Petrol: 'PETROL',
    Diesel: 'DIESEL'
} as const;
export type VehicleFuelTypeEnum = typeof VehicleFuelTypeEnum[keyof typeof VehicleFuelTypeEnum];


export function instanceOfVehicleFuelTypeEnum(value: any): boolean {
    for (const key in VehicleFuelTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(VehicleFuelTypeEnum, key)) {
            if (VehicleFuelTypeEnum[key as keyof typeof VehicleFuelTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VehicleFuelTypeEnumFromJSON(json: any): VehicleFuelTypeEnum {
    return VehicleFuelTypeEnumFromJSONTyped(json, false);
}

export function VehicleFuelTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleFuelTypeEnum {
    return json as VehicleFuelTypeEnum;
}

export function VehicleFuelTypeEnumToJSON(value?: VehicleFuelTypeEnum | null): any {
    return value as any;
}

export function VehicleFuelTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): VehicleFuelTypeEnum {
    return value as VehicleFuelTypeEnum;
}

