/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The method of water heating
 * @export
 */
export const WaterHeatingEnum = {
    Gas: 'GAS',
    Lpg: 'LPG',
    ElectricResistance: 'ELECTRIC_RESISTANCE',
    ElectricHeatPump: 'ELECTRIC_HEAT_PUMP',
    Solar: 'SOLAR'
} as const;
export type WaterHeatingEnum = typeof WaterHeatingEnum[keyof typeof WaterHeatingEnum];


export function instanceOfWaterHeatingEnum(value: any): boolean {
    for (const key in WaterHeatingEnum) {
        if (Object.prototype.hasOwnProperty.call(WaterHeatingEnum, key)) {
            if (WaterHeatingEnum[key as keyof typeof WaterHeatingEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WaterHeatingEnumFromJSON(json: any): WaterHeatingEnum {
    return WaterHeatingEnumFromJSONTyped(json, false);
}

export function WaterHeatingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaterHeatingEnum {
    return json as WaterHeatingEnum;
}

export function WaterHeatingEnumToJSON(value?: WaterHeatingEnum | null): any {
    return value as any;
}

export function WaterHeatingEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): WaterHeatingEnum {
    return value as WaterHeatingEnum;
}

